# Generated by Django 5.1.15 on 2026-09-11 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('tagline', models.CharField(blank=True, help_text='Brief commercial summary', max_length=255)),
                ('description', models.TextField(help_text='Detailed industrial overview of product')),
                ('raw_material', models.CharField(help_text='Botanical / origin feedstock (e.g. Musa acuminata pseudostem)', max_length=255)),
                ('extraction_method', models.TextField(help_text='Mechanical decortication, chemical, or biological retting')),
                ('processing', models.TextField(help_text='Post-extraction drying, combing, carding, degumming, sorting')),
                ('supplier_notes', models.TextField(blank=True, help_text='Supplier-reported observations, lot variability, seasonal supply factors')),
                ('verified_specs', models.JSONField(blank=True, default=dict, help_text="Structured dict of certified laboratory-tested metrics. E.g.: {'Tensile Strength': {'value': '580-720 MPa', 'test_method': 'ASTM D3822', 'tolerance': '±5%'}}")),
                ('provisional_specs', models.JSONField(blank=True, default=dict, help_text="Structured dict of supplier-reported / provisional estimates. E.g.: {'Estimated Microfibril Angle': {'value': '11°-13°', 'status': 'Supplier Estimated - Pending Lab Confirmation'}}")),
                ('harvest_origin', models.CharField(blank=True, default='Direct Mill Origins / Certified Estates', max_length=150)),
                ('moq', models.CharField(default='1 FCL / 10 Metric Tons', help_text='Minimum Order Quantity', max_length=100)),
                ('packaging_details', models.TextField(blank=True, help_text='Hydraulically compressed bales, palletized, PP wrapping, custom moisture barrier')),
                ('hs_code', models.CharField(blank=True, help_text='Harmonized System Tariff Code', max_length=50)),
                ('applications', models.JSONField(blank=True, default=list, help_text='List of industrial use cases (e.g. Automotive, Paper, Textile)')),
                ('is_featured', models.BooleanField(default=False, help_text='Feature prominently on homepage')),
                ('is_active', models.BooleanField(default=True, help_text='Display publicly on catalog')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category')),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('doc_type', models.CharField(choices=[('TDS', 'Technical Data Sheet (TDS)'), ('COA', 'Certificate of Analysis (COA)'), ('SPEC', 'Technical Specifications Summary'), ('COMPLIANCE', 'Phytosanitary / Export Compliance Document')], default='TDS', max_length=20)),
                ('document_file', models.FileField(upload_to='products/documents/')),
                ('file_size', models.CharField(blank=True, help_text="e.g. '340 KB PDF'", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='products.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/images/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
