# Generated by Django 5.1.15 on 2026-09-11 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(db_index=True, editable=False, max_length=30, unique=True)),
                ('name', models.CharField(max_length=150, verbose_name='Full Name / Representative')),
                ('company', models.CharField(max_length=200, verbose_name='Company / Enterprise Legal Name')),
                ('country', models.CharField(max_length=100, verbose_name='Buyer Country')),
                ('email', models.EmailField(max_length=254, verbose_name='Official Corporate Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Phone / WhatsApp (Optional)')),
                ('product_interest', models.CharField(blank=True, max_length=255, verbose_name='Product or Custom Sourcing Interest')),
                ('quantity', models.CharField(help_text="e.g., '15 Metric Tons / month' or '2 x 40ft HQ FCL'", max_length=150, verbose_name='Estimated Quantity & Volume')),
                ('application', models.CharField(help_text='e.g., Automotive Composites, Bio-packaging, Technical Textiles, Pulp', max_length=255, verbose_name='Intended Industrial Application')),
                ('technical_requirements', models.TextField(blank=True, help_text='Specify required tensile strength, fiber length, moisture %, or lab protocols.', verbose_name='Technical & Quality Requirements')),
                ('technical_file', models.FileField(blank=True, help_text='Upload PDF, DOC, or image (Max 10MB)', null=True, upload_to='rfq/specifications/', verbose_name='Technical Drawing / Specification Sheet (Optional)')),
                ('packaging', models.CharField(blank=True, default='Standard Compressed Bales', help_text='e.g., Compressed Bales (100kg), Palletized, Custom Poly-woven', max_length=150, verbose_name='Preferred Packaging')),
                ('delivery_country', models.CharField(max_length=100, verbose_name='Destination Country / Port of Discharge')),
                ('incoterms', models.CharField(choices=[('FOB', 'FOB (Free on Board)'), ('CIF', 'CIF (Cost, Insurance & Freight)'), ('CFR', 'CFR (Cost & Freight)'), ('EXW', 'EXW (Ex Works)'), ('FCA', 'FCA (Free Carrier)'), ('DDP', 'DDP (Delivered Duty Paid)')], default='CIF', max_length=20, verbose_name='Preferred Incoterms')),
                ('message', models.TextField(blank=True, verbose_name='Commercial Notes / Additional Instructions')),
                ('sample_request', models.BooleanField(default=False, help_text='Check if physical verification sample lot is required prior to commercial quotation.', verbose_name='Request Physical Sample Kit')),
                ('consent', models.BooleanField(default=True, help_text='I confirm this is an authentic commercial inquiry and agree to B2B processing terms.', verbose_name='B2B Commercial Consent')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('REVIEWING', 'Reviewing'), ('QUOTED', 'Quoted'), ('SAMPLE', 'Sample Dispatched'), ('NEGOTIATION', 'Negotiation'), ('WON', 'Won / Order Confirmed'), ('LOST', 'Lost / Closed')], default='NEW', max_length=30, verbose_name='RFQ Pipeline Status')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes: mill allocation, shipping line quotes, follow-up log', verbose_name='Internal Sourcing Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfqs', to='products.product', verbose_name='Target Catalog Product')),
            ],
            options={
                'verbose_name': 'RFQ',
                'verbose_name_plural': 'RFQs',
                'ordering': ['-created_at'],
            },
        ),
    ]
