# Generated by Django 5.1.15 on 2026-09-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('SOURCING', 'Direct Sourcing & Origin Verification'), ('SPECS', 'Technical Specifications & Lab Testing'), ('SAMPLES', 'Sample Dispatch & Evaluation Kits'), ('LOGISTICS', 'Shipping, Incoterms & Packaging'), ('COMMERCIAL', 'Payment Terms & Trade Contracts')], default='SOURCING', max_length=50)),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField(help_text='Detailed B2B answer. Supports HTML/paragraphs.')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('HERO_SUBTITLE', 'Homepage Hero Subtitle'), ('ABOUT_MISSION', 'About Us - Core Mission Statement'), ('QUALITY_GUARANTEE', 'Quality & Process - Laboratory Verification Guarantee'), ('SOURCING_NETWORK', 'Sourcing Services - Direct Mill Network Summary'), ('CONTACT_NOTICE', 'Contact Desk - Commercial Notice')], max_length=50, unique=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CMS Page Content Block',
                'verbose_name_plural': 'CMS Page Content Blocks',
            },
        ),
    ]
